"use client";

import React, { useState, useEffect, useId, useRef } from "react";
import mermaid from "mermaid";
import {
  Copy,
  Check,
  Maximize2,
  Minimize2,
  AlertTriangle,
  Loader2,
  FileCode,
  ZoomIn,
  ZoomOut,
  RotateCcw,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

let isMermaidInitialized = false;

function initMermaidOnce() {
  if (typeof window !== "undefined" && !isMermaidInitialized) {
    mermaid.initialize({
      startOnLoad: false,
      theme: "default",
      securityLevel: "loose",
      fontFamily: "inherit",
      flowchart: {
        htmlLabels: true,
        curve: "basis",
      },
      sequence: {
        diagramMarginX: 20,
        diagramMarginY: 20,
      },
    });
    isMermaidInitialized = true;
  }
}

interface MermaidRendererProps {
  code: string;
  className?: string;
  title?: string;
}

export function MermaidRenderer({
  code,
  className,
  title = "Process & Architecture Flow",
}: MermaidRendererProps) {
  const [svgHtml, setSvgHtml] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [hasError, setHasError] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [copied, setCopied] = useState<boolean>(false);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [zoomLevel, setZoomLevel] = useState<number>(1);

  const containerRef = useRef<HTMLDivElement>(null);
  const cleanCode = code.trim();
  const reactId = useId().replace(/:/g, "_");
  const renderId = `mermaid_${reactId}_${Math.random().toString(36).substring(2, 7)}`;

  useEffect(() => {
    initMermaidOnce();

    if (!cleanCode) {
      setIsLoading(false);
      return;
    }

    let isMounted = true;
    setIsLoading(true);
    setHasError(false);
    setErrorMessage("");

    const renderDiagram = async () => {
      try {
        // Render SVG asynchronously
        const { svg } = await mermaid.render(renderId, cleanCode);
        if (isMounted) {
          setSvgHtml(svg);
          setIsLoading(false);
        }
      } catch (err: any) {
        if (isMounted) {
          console.warn("Mermaid diagram compilation error:", err);
          setHasError(true);
          setErrorMessage(err?.message || "Syntax error in diagram definition");
          setIsLoading(false);
        }
        // Cleanup leftover error element generated by mermaid in body
        const errElement = document.getElementById(renderId);
        if (errElement) {
          errElement.remove();
        }
      }
    };

    renderDiagram();

    return () => {
      isMounted = false;
      const el = document.getElementById(renderId);
      if (el) el.remove();
    };
  }, [cleanCode, renderId]);

  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(cleanCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  };

  const handleZoomIn = () => setZoomLevel((z) => Math.min(z + 0.25, 2.5));
  const handleZoomOut = () => setZoomLevel((z) => Math.max(z - 0.25, 0.5));
  const handleResetZoom = () => setZoomLevel(1);

  return (
    <>
      <div
        className={cn(
          "group/diagram relative my-3 flex flex-col rounded-xl border border-gray-200 bg-white shadow-xs dark:border-border dark:bg-card/90 overflow-hidden transition-all",
          className
        )}
      >
        {/* Top Header Bar */}
        <div className="flex items-center justify-between border-b border-gray-100 dark:border-border/60 bg-gray-50/80 dark:bg-secondary/40 px-3.5 py-2 text-xs">
          <div className="flex items-center gap-2">
            <span className="flex h-2 w-2 rounded-full bg-[#6C63FF]" />
            <span className="font-semibold text-gray-700 dark:text-gray-200 tracking-tight">
              {title}
            </span>
          </div>

          <div className="flex items-center gap-1.5">
            <button
              onClick={handleCopyCode}
              className="inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-200/60 dark:hover:bg-secondary transition-colors cursor-pointer"
              title="Copy Mermaid Code"
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3 text-emerald-500" />
                  <span className="text-emerald-600 dark:text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3 text-gray-500" />
                  <span>Copy Diagram</span>
                </>
              )}
            </button>

            {!hasError && !isLoading && (
              <button
                onClick={() => setIsFullscreen(true)}
                className="inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-200/60 dark:hover:bg-secondary transition-colors cursor-pointer"
                title="Expand Fullscreen"
              >
                <Maximize2 className="h-3 w-3 text-gray-500" />
                <span className="hidden sm:inline">Fullscreen</span>
              </button>
            )}
          </div>
        </div>

        {/* Content Area */}
        <div className="relative min-h-[140px] p-4 flex items-center justify-center">
          {isLoading ? (
            /* Skeleton Loading State */
            <div className="flex flex-col items-center justify-center gap-2.5 py-8 text-center animate-pulse">
              <Loader2 className="h-6 w-6 animate-spin text-[#6C63FF]" />
              <div className="space-y-1">
                <p className="text-xs font-medium text-gray-700 dark:text-gray-300">
                  Compiling visual diagram...
                </p>
                <p className="text-[11px] text-gray-400">
                  Parsing nodes, relationships, and styling definitions
                </p>
              </div>
            </div>
          ) : hasError ? (
            /* Error Fallback State */
            <div className="w-full space-y-3 p-2 text-left">
              <div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2.5 text-xs text-amber-800 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-300">
                <AlertTriangle className="h-4 w-4 shrink-0 text-amber-600" />
                <div>
                  <span className="font-semibold">Diagram could not render.</span>
                  <span className="ml-1 opacity-90">{errorMessage}</span>
                </div>
              </div>

              <div className="rounded-lg bg-gray-900 p-3 font-mono text-[11px] text-gray-200 overflow-x-auto">
                <pre>{cleanCode}</pre>
              </div>
            </div>
          ) : (
            /* Compiled SVG Container: horizontally scrollable on mobile */
            <div
              ref={containerRef}
              className="w-full overflow-x-auto py-2 flex justify-center custom-scrollbar"
              dangerouslySetInnerHTML={{ __html: svgHtml }}
            />
          )}
        </div>
      </div>

      {/* Fullscreen Expand Modal */}
      {isFullscreen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4 animate-in fade-in duration-200">
          <div className="relative flex flex-col w-full max-w-5xl h-[85vh] rounded-2xl bg-white dark:bg-card border border-border shadow-2xl overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-border bg-secondary/30 px-5 py-3">
              <div className="flex items-center gap-2">
                <span className="flex h-2.5 w-2.5 rounded-full bg-[#6C63FF]" />
                <h3 className="text-sm font-bold text-foreground">{title}</h3>
                <span className="rounded bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary">
                  {Math.round(zoomLevel * 100)}%
                </span>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleZoomIn}
                  className="rounded-lg border border-border p-1.5 text-muted-foreground hover:bg-secondary hover:text-foreground"
                  title="Zoom In"
                >
                  <ZoomIn className="h-4 w-4" />
                </button>
                <button
                  onClick={handleZoomOut}
                  className="rounded-lg border border-border p-1.5 text-muted-foreground hover:bg-secondary hover:text-foreground"
                  title="Zoom Out"
                >
                  <ZoomOut className="h-4 w-4" />
                </button>
                <button
                  onClick={handleResetZoom}
                  className="rounded-lg border border-border p-1.5 text-muted-foreground hover:bg-secondary hover:text-foreground"
                  title="Reset Zoom"
                >
                  <RotateCcw className="h-4 w-4" />
                </button>
                <button
                  onClick={handleCopyCode}
                  className="flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-secondary hover:text-foreground"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                  <span>{copied ? "Copied" : "Copy Code"}</span>
                </button>
                <button
                  onClick={() => {
                    setIsFullscreen(false);
                    setZoomLevel(1);
                  }}
                  className="rounded-lg border border-border p-1.5 text-muted-foreground hover:bg-rose-50 hover:text-rose-600 transition-colors"
                  title="Close Fullscreen"
                >
                  <Minimize2 className="h-4 w-4" />
                </button>
              </div>
            </div>

            {/* Modal Body with Zoom Pan */}
            <div className="flex-1 overflow-auto p-6 flex items-center justify-center bg-gray-50/50 dark:bg-card/50">
              <div
                style={{
                  transform: `scale(${zoomLevel})`,
                  transformOrigin: "center center",
                  transition: "transform 0.15s ease-out",
                }}
                className="max-w-none flex justify-center"
                dangerouslySetInnerHTML={{ __html: svgHtml }}
              />
            </div>
          </div>
        </div>
      )}
    </>
  );
}
